using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CalisBakalimEnik.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// Turns <c>security_events</c> into a monthly range-partitioned table.
    /// </summary>
    /// <remarks>
    /// <para><b>Run this before launch.</b> It rewrites the table under an
    /// ACCESS EXCLUSIVE lock, which is instant while the table holds a few
    /// hundred rows and a maintenance window once it holds millions. That
    /// asymmetry is the whole reason for doing it now: the table is append-only
    /// and gains a row on every login, MFA challenge and token refresh, so at a
    /// thousand users it is on the order of eighteen million rows a year.</para>
    ///
    /// <para>Deleting a year out of a table that size marks every row dead,
    /// writes a WAL record for each, and leaves the space occupied until
    /// VACUUM catches up. Dropping a partition unlinks a file.</para>
    ///
    /// <para>The primary key has to become <c>(id, occurred_at)</c>: a unique
    /// index on a partitioned table must contain the partition key. EF's model
    /// still declares <c>id</c> alone, which stays correct — the id comes from
    /// one sequence shared by every partition, so it is still globally unique,
    /// and it remains the leading column of the PK index so the admin viewer's
    /// keyset paging still has an index to walk.</para>
    ///
    /// <para>EF does not model partitions. A later migration touching this
    /// table will not know about them — that is the standing cost of this
    /// change, and it is written down in docs/DATABASE.md §6.</para>
    /// </remarks>
    public partial class PartitionSecurityEvents : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Postgres does not rename a table's indexes and constraints along
            // with it, and index names are unique per schema — so the old ones
            // have to move aside before the new table can claim them.
            migrationBuilder.Sql("""
                ALTER TABLE security_events RENAME TO security_events_legacy;
                ALTER TABLE security_events_legacy
                    RENAME CONSTRAINT pk_security_events TO pk_security_events_legacy;
                ALTER INDEX ix_security_events_ip   RENAME TO ix_security_events_legacy_ip;
                ALTER INDEX ix_security_events_type RENAME TO ix_security_events_legacy_type;
                ALTER INDEX ix_security_events_user RENAME TO ix_security_events_legacy_user;
                """);

            // Nor does renaming a table rename the sequence behind its identity
            // column. Left alone, the new table cannot have
            // security_events_id_seq either — Postgres would quietly settle for
            // security_events_id_seq1 and leave a sequence named after a table
            // that no longer exists.
            migrationBuilder.Sql("""
                DO $$
                DECLARE seq text;
                BEGIN
                    seq := pg_get_serial_sequence('security_events_legacy', 'id');

                    IF seq IS NOT NULL THEN
                        EXECUTE format(
                            'ALTER SEQUENCE %s RENAME TO security_events_legacy_id_seq', seq);
                    END IF;
                END $$;
                """);

            migrationBuilder.Sql("""
                CREATE TABLE security_events (
                    id          bigint GENERATED BY DEFAULT AS IDENTITY,
                    user_id     uuid,
                    event_type  smallint NOT NULL,
                    succeeded   boolean NOT NULL,
                    ip          character varying(64),
                    user_agent  character varying(400),
                    detail      jsonb NOT NULL DEFAULT '{}',
                    occurred_at timestamp with time zone NOT NULL,
                    CONSTRAINT pk_security_events PRIMARY KEY (id, occurred_at)
                ) PARTITION BY RANGE (occurred_at);
                """);

            // Declared on the parent, so every partition — including ones
            // created years from now — inherits them without being told.
            migrationBuilder.Sql("""
                CREATE INDEX ix_security_events_ip
                    ON security_events (ip, occurred_at DESC);
                CREATE INDEX ix_security_events_type
                    ON security_events (event_type, occurred_at DESC);
                CREATE INDEX ix_security_events_user
                    ON security_events (user_id, occurred_at DESC);
                """);

            // The catch-all. Without it, a row whose month has no partition is
            // REJECTED — and since a row is written on every login, a
            // maintenance job that fell behind would stop people signing in.
            // With it, the same failure is a table quietly filling up, which
            // PartitionMaintenance reports as an error every night.
            migrationBuilder.Sql(
                "CREATE TABLE security_events_default PARTITION OF security_events DEFAULT;");

            // Enough partitions to cover the existing rows and a year ahead.
            // PartitionMaintenance keeps the window rolling after this.
            migrationBuilder.Sql("""
                DO $$
                DECLARE
                    m         date;
                    last      date;
                    part      text;
                BEGIN
                    SELECT date_trunc('month', COALESCE(MIN(occurred_at), now()))::date
                      INTO m
                      FROM security_events_legacy;

                    last := (date_trunc('month', now()) + interval '12 months')::date;

                    WHILE m < last LOOP
                        part := 'security_events_' || to_char(m, 'YYYY_MM');

                        -- Explicit +00, not a bare date. A date literal is cast
                        -- using the SESSION time zone, so this same migration
                        -- run on a server set to Europe/Istanbul would put the
                        -- month boundary at 21:00 the previous day and file
                        -- three hours of every month in the wrong partition.
                        EXECUTE format(
                            'CREATE TABLE IF NOT EXISTS %I PARTITION OF security_events '
                            'FOR VALUES FROM (%L) TO (%L)',
                            part,
                            to_char(m, 'YYYY-MM-DD') || ' 00:00:00+00',
                            to_char((m + interval '1 month')::date, 'YYYY-MM-DD')
                                || ' 00:00:00+00');

                        m := (m + interval '1 month')::date;
                    END LOOP;
                END $$;
                """);

            migrationBuilder.Sql("""
                INSERT INTO security_events
                    (id, user_id, event_type, succeeded, ip, user_agent, detail, occurred_at)
                SELECT
                    id, user_id, event_type, succeeded, ip, user_agent, detail, occurred_at
                FROM security_events_legacy;
                """);

            // Explicit ids do not advance the identity sequence, so without
            // this the next insert reuses id 1 and violates the primary key.
            // is_called = false makes nextval return exactly this value, which
            // is also correct for an empty table (max 0 → next 1).
            migrationBuilder.Sql("""
                SELECT setval(
                    pg_get_serial_sequence('security_events', 'id'),
                    COALESCE((SELECT MAX(id) FROM security_events), 0) + 1,
                    false);
                """);

            migrationBuilder.Sql("DROP TABLE security_events_legacy;");

            // ── the application's three capabilities ──────────────────────
            //
            // The running app connects as a role that CANNOT issue DDL, and
            // that boundary is worth keeping: an injection anywhere becomes
            // arbitrary schema access the moment the app can CREATE. But
            // partitions have to be created and dropped while the service is
            // running, by the service.
            //
            // SECURITY DEFINER is the way out. These run as the role that owns
            // the schema, and each does exactly one thing to exactly one
            // allowlisted table — so the app gains the capability without
            // gaining the privilege.
            //
            // SET search_path is not decoration: without it a caller can put
            // their own schema in front of pg_catalog and have a definer
            // function resolve to their code. `public` is deliberately NOT in
            // the path — the first version had `pg_catalog, public`, which made
            // an unqualified CREATE TABLE try to create in pg_catalog and fail
            // on every month with 42501. Every object below is qualified by
            // hand instead, which is what the Postgres manual asks for anyway.
            migrationBuilder.Sql("""
                CREATE OR REPLACE FUNCTION ensure_month_partitions(
                    p_table text, p_months int)
                RETURNS int
                LANGUAGE plpgsql
                SECURITY DEFINER
                SET search_path = pg_catalog, pg_temp
                AS $fn$
                DECLARE
                    m      date;
                    last   date;
                    part   text;
                    made   int := 0;
                BEGIN
                    IF p_table <> 'security_events' THEN
                        RAISE EXCEPTION
                            'ensure_month_partitions: % is not managed here', p_table;
                    END IF;

                    p_months := least(greatest(coalesce(p_months, 6), 1), 120);

                    m    := date_trunc('month', now() AT TIME ZONE 'UTC')::date;
                    last := (m + make_interval(months => p_months))::date;

                    WHILE m <= last LOOP
                        part := p_table || '_' || to_char(m, 'YYYY_MM');

                        IF to_regclass('public.' || part) IS NULL THEN
                            EXECUTE format(
                                'CREATE TABLE public.%I PARTITION OF public.%I '
                                'FOR VALUES FROM (%L) TO (%L)',
                                part, p_table,
                                to_char(m, 'YYYY-MM-DD') || ' 00:00:00+00',
                                to_char((m + interval '1 month')::date, 'YYYY-MM-DD')
                                    || ' 00:00:00+00');

                            made := made + 1;
                        END IF;

                        m := (m + interval '1 month')::date;
                    END LOOP;

                    RETURN made;
                END
                $fn$;
                """);

            // Retention for a partitioned table.
            migrationBuilder.Sql("""
                CREATE OR REPLACE FUNCTION drop_aged_partitions(
                    p_table text, p_cutoff timestamptz)
                RETURNS int
                LANGUAGE plpgsql
                SECURITY DEFINER
                SET search_path = pg_catalog, pg_temp
                AS $fn$
                DECLARE
                    r        record;
                    m        date;
                    dropped  int := 0;
                BEGIN
                    IF p_table <> 'security_events' THEN
                        RAISE EXCEPTION
                            'drop_aged_partitions: % is not managed here', p_table;
                    END IF;

                    FOR r IN
                        SELECT c.relname AS name
                        FROM pg_inherits i
                        JOIN pg_class c ON c.oid = i.inhrelid
                        JOIN pg_class parent ON parent.oid = i.inhparent
                        WHERE parent.relname = p_table
                          AND parent.relnamespace = 'public'::regnamespace
                          -- Anchored, and it excludes the DEFAULT partition by
                          -- construction. A partition nobody here created is a
                          -- partition nobody here drops.
                          AND c.relname ~ ('^' || p_table || '_[0-9]{4}_[0-9]{2}$')
                    LOOP
                        m := to_date(right(r.name, 7), 'YYYY_MM');

                        -- The UPPER bound, not the lower: a partition is only
                        -- safe to drop once the whole month is behind the
                        -- cutoff, or the current month goes with it.
                        IF ((m + interval '1 month') AT TIME ZONE 'UTC') <= p_cutoff THEN
                            EXECUTE format('DROP TABLE public.%I', r.name);
                            dropped := dropped + 1;
                        END IF;
                    END LOOP;

                    RETURN dropped;
                END
                $fn$;
                """);

            // The alarm. Privileges on a partition are its own and reads
            // normally go through the parent, so counting the default
            // partition directly needs a definer function too.
            migrationBuilder.Sql("""
                CREATE OR REPLACE FUNCTION default_partition_rows(p_table text)
                RETURNS bigint
                LANGUAGE plpgsql
                SECURITY DEFINER
                SET search_path = pg_catalog, pg_temp
                AS $fn$
                DECLARE n bigint;
                BEGIN
                    IF p_table <> 'security_events' THEN
                        RAISE EXCEPTION
                            'default_partition_rows: % is not managed here', p_table;
                    END IF;

                    EXECUTE format('SELECT count(*) FROM public.%I', p_table || '_default')
                    INTO n;

                    RETURN n;
                END
                $fn$;
                """);

            // Postgres grants EXECUTE to PUBLIC on a new function by default,
            // which is what lets the app role call these. Acceptable because
            // each is allowlisted to one table and can do nothing else; a
            // deployment wanting it tighter can REVOKE from PUBLIC and GRANT to
            // the app role by name. See docs/DATABASE.md §6.
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                ALTER TABLE security_events RENAME TO security_events_partitioned;
                ALTER TABLE security_events_partitioned
                    RENAME CONSTRAINT pk_security_events TO pk_security_events_partitioned;
                ALTER INDEX ix_security_events_ip   RENAME TO ix_security_events_part_ip;
                ALTER INDEX ix_security_events_type RENAME TO ix_security_events_part_type;
                ALTER INDEX ix_security_events_user RENAME TO ix_security_events_part_user;
                """);

            migrationBuilder.Sql("""
                DO $$
                DECLARE seq text;
                BEGIN
                    seq := pg_get_serial_sequence('security_events_partitioned', 'id');

                    IF seq IS NOT NULL THEN
                        EXECUTE format(
                            'ALTER SEQUENCE %s RENAME TO security_events_part_id_seq', seq);
                    END IF;
                END $$;
                """);

            migrationBuilder.Sql("""
                CREATE TABLE security_events (
                    id          bigint GENERATED BY DEFAULT AS IDENTITY,
                    user_id     uuid,
                    event_type  smallint NOT NULL,
                    succeeded   boolean NOT NULL,
                    ip          character varying(64),
                    user_agent  character varying(400),
                    detail      jsonb NOT NULL DEFAULT '{}',
                    occurred_at timestamp with time zone NOT NULL,
                    CONSTRAINT pk_security_events PRIMARY KEY (id)
                );
                """);

            migrationBuilder.Sql("""
                INSERT INTO security_events
                    (id, user_id, event_type, succeeded, ip, user_agent, detail, occurred_at)
                SELECT
                    id, user_id, event_type, succeeded, ip, user_agent, detail, occurred_at
                FROM security_events_partitioned;
                """);

            migrationBuilder.Sql("""
                SELECT setval(
                    pg_get_serial_sequence('security_events', 'id'),
                    COALESCE((SELECT MAX(id) FROM security_events), 0) + 1,
                    false);
                """);

            migrationBuilder.Sql("""
                CREATE INDEX ix_security_events_ip
                    ON security_events (ip, occurred_at DESC);
                CREATE INDEX ix_security_events_type
                    ON security_events (event_type, occurred_at DESC);
                CREATE INDEX ix_security_events_user
                    ON security_events (user_id, occurred_at DESC);
                """);

            // Dropping the parent drops every partition with it.
            migrationBuilder.Sql("DROP TABLE security_events_partitioned;");

            migrationBuilder.Sql("""
                DROP FUNCTION IF EXISTS ensure_month_partitions(text, int);
                DROP FUNCTION IF EXISTS drop_aged_partitions(text, timestamptz);
                DROP FUNCTION IF EXISTS default_partition_rows(text);
                """);
        }
    }
}
